export { module1Data } from './module1';
export { module2Data } from './module2';
export { module3Data } from './module3';
export { module4Data } from './module4';
export { module5Data } from './module5';
export { module6Data } from './module6';
export { module7Data } from './module7';
export { module8Data } from './module8';
export { module9Data } from './module9';
export { module10Data } from './module10';
export { module11Data } from './module11';
export { module12Data } from './module12';
export { module13Data } from './module13';
export { module14Data } from './module14';
export { module15Data } from './module15';
export { module16Data } from './module16';
export { module17Data } from './module17';
export { module18Data } from './module18';
// All 18 modules have been created
